name: flutter_bt_print
description: Bluetooth thermal printing plugin for Flutter supporting ESC/POS printers, image and PDF printing.
version: 0.0.1
homepage: https://github.com/rahmanprofile/flutter_bt_print
repository: https://github.com/rahmanprofile/flutter_bt_print
issue_tracker: https://github.com/rahmanprofile/flutter_bt_print/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.11.3
  printing: ^5.14.2
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.rahman_profile.flutter_bt_print
        pluginClass: FlutterBtPrintPlugin
      ios:
        pluginClass: FlutterBtPrintPlugin


  assets:
    - assets/flutter_bt_print.png