name: flutter_bt_print
description: A Flutter plugin for Bluetooth thermal printing (text, images, PDFs) on Android and iOS.
version: 0.0.1
homepage: https://github.com/rahmanprofile/flutter_bt_print

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  pdf:
  printing:
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.rahman_profile.flutter_bt_print
        pluginClass: FlutterBtPrintPlugin
      ios:
        pluginClass: FlutterBtPrintPlugin
